// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID
	Url           string
	Title         string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	UserID        uuid.NullUUID
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	ID        uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    uuid.NullUUID
	FeedID    uuid.NullUUID
}

type Post struct {
	ID          uuid.UUID
	Url         string
	Userid      uuid.NullUUID
	Title       string
	Description sql.NullString
	PublishedAt time.Time
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	FeedID      uuid.NullUUID
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ApiKey    string
}
